givery-bootcamp/dena-2024-team3

backend/internal/application/usecase/post_usecase.go, backend/internal/domain/model/post.go, backend/internal/domain/model/user.go, backend/internal/domain/repository/post_repository.go, backend/internal/infrastructure/persistence/datastore/entity/post.go, backend/internal/infrastructure/persistence/datastore/entity/user.go, backend/internal/infrastructure/persistence/datastore/post_repository.go, backend/internal/interface/api/handler/hello_world_handler.go, backend/internal/interface/api/handler/post_handler.go, backend/internal/interface/api/router/router.go
close #5 
リクエスト
```
curl --location 'http://localhost:9000/posts'
```
レスポンス
```json
[
{
"id": 1,
"title": "test1",
"body": "質問1\n改行",
"user": {
"id": 1,
"name": "taro"
},
"created_at": "0001-01-01T00:00:00Z",
"updated_at": "0001-01-01T00:00:00Z"
},
{
"id": 2,
"title": "test2",
"body": "質問2\n改行",
"user": {
"id": 1,
"name": "taro"
},
"created_at": "0001-01-01T00:00:00Z",
"updated_at": "0001-01-01T00:00:00Z"
}
]
```
=> 投稿一覧取得API作成

backend/internal/application/usecase/post_usecase.go, backend/internal/domain/repository/post_repository.go, backend/internal/exception/exception.go, backend/internal/infrastructure/persistence/datastore/post_repository.go, backend/internal/interface/api/handler/post_handler.go, backend/internal/interface/api/router/router.go
close #6 
リクエスト
```
curl --location 'http://localhost:9000/posts/1'
```
レスポンス
```json
{
"id": 1,
"title": "test1",
"body": "質問1\n改行",
"user": {
"id": 1,
"name": "taro"
},
"created_at": "0001-01-01T00:00:00Z",
"updated_at": "0001-01-01T00:00:00Z"
}
```
=> 投稿詳細取得APIの作成

.gitignore, backend/.env.sample, backend/go.mod, backend/go.sum, backend/internal/application/usecase/user_usecase.go, backend/internal/config/config.go, backend/internal/domain/model/user.go, backend/internal/domain/repository/user_repository.go, backend/internal/exception/exception.go, backend/internal/infrastructure/persistence/datastore/user_repository.go, backend/internal/interface/api/handler/user_handler.go, backend/internal/interface/api/middleware/auth.go, backend/internal/interface/api/router/router.go, backend/internal/pkg/jwt/jwt.go, docker-compose.yml
close #17 
リクエスト
```
curl --location 'http://localhost:9000/api/signin' \
--header 'Content-Type: application/json' \
--data '{
"name": "taro",
"password": "password"
}'
```
レスポンス
```json
{
"id": 1,
"name": "taro"
}
```
```json
{
"message": "サインインに失敗しました",
"code": 0
}
```
=> サインインAPIの作成

backend/internal/application/usecase/user_usecase.go, backend/internal/config/config.go, backend/internal/domain/repository/user_repository.go, backend/internal/infrastructure/persistence/datastore/user_repository.go, backend/internal/interface/api/handler/user_handler.go, backend/internal/interface/api/middleware/auth.go, backend/internal/interface/api/middleware/error_handler.go, backend/internal/interface/api/router/router.go, backend/internal/pkg/jwt/jwt.go
=> ログインしているユーザーを取得するAPIを作成

backend/internal/application/usecase/post_usecase.go, backend/internal/domain/repository/post_repository.go, backend/internal/infrastructure/persistence/datastore/post_repository.go, backend/internal/interface/api/handler/post_handler.go
=> GET /posts にlimit とoffsetをつける

backend/internal/interface/api/handler/user_handler.go, backend/internal/interface/api/middleware/auth.go, backend/internal/interface/api/router/router.go
close #19 
元のissueを見る感じ、認証なしなので、あれば消すを想定していそうな雰囲気を感じて、ログインしていない状態でも200を返すようにしている
=> サインアウトのAPI作成

backend/internal/interface/api/middleware/cors.go
Authorizationヘッダーなどを使う場合はAllow Headerに入れないといけない
=> Allow Headerを追加

frontend/package-lock.json, frontend/package.json, frontend/src/api/ApiClient.ts, frontend/src/api/core/ApiError.ts, frontend/src/api/core/ApiRequestOptions.ts, frontend/src/api/core/ApiResult.ts, frontend/src/api/core/BaseHttpRequest.ts, frontend/src/api/core/CancelablePromise.ts, frontend/src/api/core/FetchHttpRequest.ts, frontend/src/api/core/OpenAPI.ts, frontend/src/api/core/request.ts, frontend/src/api/index.ts, frontend/src/api/models/model_Post.ts, frontend/src/api/models/model_User.ts, frontend/src/api/models/model_UserSigninParam.ts, frontend/src/api/services/AuthService.ts, frontend/src/api/services/PostService.ts, frontend/src/api/services/UserService.ts, frontend/src/app/AppRoute.tsx, frontend/src/features/helloworld/HelloWorld.tsx, frontend/src/features/posts/posts.tsx, frontend/src/shared/hooks/index.ts, frontend/src/shared/services/API.ts, frontend/src/shared/store/HelloSlice.ts, frontend/src/shared/store/postsSlice.ts, frontend/tsconfig.json
=> swaggerの生成したモデルを使うようにした

backend/internal/interface/api/handler/post_handler.go
=> クエリにデフォルトを追加した

backend/internal/application/usecase/post_usecase.go, backend/internal/domain/repository/post_repository.go, backend/internal/infrastructure/persistence/datastore/post_repository.go, backend/internal/interface/api/handler/post_handler.go
=> refactor: GetByIdでuserIdを使わない

backend/internal/application/usecase/post_usecase.go, backend/internal/domain/model/post.go, backend/internal/domain/repository/post_repository.go, backend/internal/domain/repository/repository_mock/post_repository_mock.go, backend/internal/exception/exception.go, backend/internal/infrastructure/persistence/datastore/entity/post.go, backend/internal/infrastructure/persistence/datastore/post_repository.go, backend/internal/interface/api/handler/post_handler.go, backend/internal/interface/api/router/router.go
=> feat: 記事更新API

backend/internal/application/usecase/post_usecase.go, backend/internal/domain/repository/post_repository.go, backend/internal/domain/repository/repository_mock/post_repository_mock.go, backend/internal/infrastructure/persistence/datastore/post_repository.go, backend/internal/interface/api/handler/post_handler.go, backend/internal/interface/api/router/router.go
=> feat: 記事削除API

backend/internal/domain/model/post_test.go, backend/internal/domain/model/user_test.go
=> add: domain modelのテスト

backend/internal/application/usecase/hello_world_usecase_test.go, backend/internal/domain/repository/repository_mock/post_repository_mock.go
close #67 
下記を参考にgotestsでunit testのコードを自動生成し、成功時と異常時のtest caseを記述しました。
https://zenn.dev/nishisuke/articles/go-generate-unit-test
https://trap.jp/post/1402/
https://github.com/cweill/gotests
=> test: HelloWorldUsecase

backend/internal/application/usecase/post_usecase_test.go
#41 , #52 でテスト追加されていなかったので、ひとまずUsecaseのテスト追加した
=> add: PostUsecaseのUpdate, Deleteのテスト

backend/internal/infrastructure/persistence/datastore/hello_world_repository_test.go, backend/internal/infrastructure/persistence/datastore/post_repository_test.go, backend/internal/infrastructure/persistence/datastore/user_repository.go, backend/internal/infrastructure/persistence/datastore/user_repository_test.go
=> HelloWorldRepository, UserRepository, PostRepository(.Delete)のユニットテスト

Makefile, backend/docs/swagger.json, backend/docs/swagger.yaml
```shell
$ make gen-swag
```
する
=> convert oas 3.0.2

backend/internal/interface/api/handler/hello_world_handler_test.go
https://github.com/givery-bootcamp/dena-2024-team3/pull/96#discussion_r1654067323
=> refactor: invalid lang parameter

backend/internal/interface/api/handler/hello_world_handler.go, backend/internal/interface/api/handler/hello_world_handler_test.go
close #74
HelloWorldHandlerのユニットテストを追加しました。
=> HelloWorldHandlerのユニットテスト

Makefile, backend/docs/swagger.json, backend/docs/swagger.yaml
Reverts givery-bootcamp/dena-2024-team3#103
=> Revert "convert oas 3.0.2"

backend/internal/application/usecase/user_usecase_test.go
close #66
UserUsecaseのユニットテストを書きました！
=> UserUsecaseのユニットテスト

backend/internal/interface/api/handler/post_handler.go, backend/internal/interface/api/handler/post_handler_test.go
=> PostHandlerのユニットテスト

frontend/src/features/postdetail/alert-delete.tsx, frontend/src/features/postdetail/postdetail.tsx, frontend/src/features/posts/posts.tsx, frontend/src/shared/services/API.ts, frontend/src/shared/store/postdetailSlice.ts
=> alertDialog使った

backend/internal/interface/api/middleware/auth.go
=> chore: middleware/authのカバレッジ上昇

backend/internal/interface/api/handler/user_handler.go, backend/internal/interface/api/middleware/auth.go, backend/internal/interface/api/middleware/auth_test.go
=> chore: DeleteCookieはエラー返さない
